### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by jensreu** [worron/ACYLS#6]
Awesome idea and project been missing this but I cant launch the editor though. First attempt I tried installing from Plasma "Get Hot New Stuff" but when that didn't work I chose to just do the proper git-clone thing. When trying to launch it I get errors though

> (run.py:8759): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (run.py:8759): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (run.py:8759): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (run.py:8759): Gtk-WARNING **: Theme parsing error: gtk.css:1878:13: '' is not a valid color name
> Traceback (most recent call last):
>   File "/home/jens/.icons/ACYLS/scripts/run.py", line 23, in <module>
>     from acyls.lib.mainwindow import MainWindow
>   File "/home/jens/.icons/ACYLS/scripts/../scripts/lib/mainwindow.py", line 9, in <module>
>     from acyls.lib.colorpage import ColorPage
>   File "/home/jens/.icons/ACYLS/scripts/../scripts/lib/colorpage.py", line 7, in <module>
>     import acyls.lib.iconchanger as iconchanger
>   File "/home/jens/.icons/ACYLS/scripts/../scripts/lib/iconchanger.py", line 6, in <module>
>     from lxml import etree
> ImportError: No module named 'lxml'

**Comment by worron** [comment]
Python lxml (usually it's `python3-lxml` package) should be installed in your system. It is preinstalled in many major distros but not in every one. Seems I missed this notion and should amend readme.

**Comment by worron** [comment]
Closed since no recent activity. Feel free to reopen if any new details come out.
